/**
 * ocrapi
 * The powerful Optical Character Recognition (OCR) APIs let you convert scanned images of pages into recognized text.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudmersiveOcrApiClientAsync);
  }
}(this, function(expect, CloudmersiveOcrApiClientAsync) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CloudmersiveOcrApiClientAsync.GetPageAngleResult();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GetPageAngleResult', function() {
    it('should create an instance of GetPageAngleResult', function() {
      // uncomment below and update the code to test GetPageAngleResult
      //var instane = new CloudmersiveOcrApiClientAsync.GetPageAngleResult();
      //expect(instance).to.be.a(CloudmersiveOcrApiClientAsync.GetPageAngleResult);
    });

    it('should have the property successful (base name: "Successful")', function() {
      // uncomment below and update the code to test the property successful
      //var instane = new CloudmersiveOcrApiClientAsync.GetPageAngleResult();
      //expect(instance).to.be();
    });

    it('should have the property angle (base name: "Angle")', function() {
      // uncomment below and update the code to test the property angle
      //var instane = new CloudmersiveOcrApiClientAsync.GetPageAngleResult();
      //expect(instance).to.be();
    });

  });

}));
