/**
 * ocrapi
 * The powerful Optical Character Recognition (OCR) APIs let you convert scanned images of pages into recognized text.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudmersiveOcrApiClientAsync);
  }
}(this, function(expect, CloudmersiveOcrApiClientAsync) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CloudmersiveOcrApiClientAsync.PreprocessingApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PreprocessingApi', function() {
    describe('preprocessingBinarize', function() {
      it('should call preprocessingBinarize successfully', function(done) {
        //uncomment below and update the code to test preprocessingBinarize
        //instance.preprocessingBinarize(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('preprocessingBinarizeAdvanced', function() {
      it('should call preprocessingBinarizeAdvanced successfully', function(done) {
        //uncomment below and update the code to test preprocessingBinarizeAdvanced
        //instance.preprocessingBinarizeAdvanced(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('preprocessingGetPageAngle', function() {
      it('should call preprocessingGetPageAngle successfully', function(done) {
        //uncomment below and update the code to test preprocessingGetPageAngle
        //instance.preprocessingGetPageAngle(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('preprocessingUnrotate', function() {
      it('should call preprocessingUnrotate successfully', function(done) {
        //uncomment below and update the code to test preprocessingUnrotate
        //instance.preprocessingUnrotate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('preprocessingUnrotateAdvanced', function() {
      it('should call preprocessingUnrotateAdvanced successfully', function(done) {
        //uncomment below and update the code to test preprocessingUnrotateAdvanced
        //instance.preprocessingUnrotateAdvanced(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('preprocessingUnskew', function() {
      it('should call preprocessingUnskew successfully', function(done) {
        //uncomment below and update the code to test preprocessingUnskew
        //instance.preprocessingUnskew(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
