/**
 * ocrapi
 * The powerful Optical Character Recognition (OCR) APIs let you convert scanned images of pages into recognized text.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/FieldResult', 'model/TableResult'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./FieldResult'), require('./TableResult'));
  } else {
    // Browser globals (root is window)
    if (!root.CloudmersiveOcrApiClientAsync) {
      root.CloudmersiveOcrApiClientAsync = {};
    }
    root.CloudmersiveOcrApiClientAsync.FormRecognitionResult = factory(root.CloudmersiveOcrApiClientAsync.ApiClient, root.CloudmersiveOcrApiClientAsync.FieldResult, root.CloudmersiveOcrApiClientAsync.TableResult);
  }
}(this, function(ApiClient, FieldResult, TableResult) {
  'use strict';




  /**
   * The FormRecognitionResult model module.
   * @module model/FormRecognitionResult
   * @version 1.3.3
   */

  /**
   * Constructs a new <code>FormRecognitionResult</code>.
   * The result of extracting form field values
   * @alias module:model/FormRecognitionResult
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>FormRecognitionResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FormRecognitionResult} obj Optional instance to populate.
   * @return {module:model/FormRecognitionResult} The populated <code>FormRecognitionResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Successful')) {
        obj['Successful'] = ApiClient.convertToType(data['Successful'], 'Boolean');
      }
      if (data.hasOwnProperty('FieldValueExtractionResult')) {
        obj['FieldValueExtractionResult'] = ApiClient.convertToType(data['FieldValueExtractionResult'], [FieldResult]);
      }
      if (data.hasOwnProperty('TableValueExtractionResults')) {
        obj['TableValueExtractionResults'] = ApiClient.convertToType(data['TableValueExtractionResults'], [TableResult]);
      }
      if (data.hasOwnProperty('Diagnostics')) {
        obj['Diagnostics'] = ApiClient.convertToType(data['Diagnostics'], ['String']);
      }
      if (data.hasOwnProperty('BestMatchFormSettingName')) {
        obj['BestMatchFormSettingName'] = ApiClient.convertToType(data['BestMatchFormSettingName'], 'String');
      }
    }
    return obj;
  }

  /**
   * True if the operation was successful, false otherwise
   * @member {Boolean} Successful
   */
  exports.prototype['Successful'] = undefined;
  /**
   * Result of form field OCR data extraction
   * @member {Array.<module:model/FieldResult>} FieldValueExtractionResult
   */
  exports.prototype['FieldValueExtractionResult'] = undefined;
  /**
   * Result of form table OCR data extraction
   * @member {Array.<module:model/TableResult>} TableValueExtractionResults
   */
  exports.prototype['TableValueExtractionResults'] = undefined;
  /**
   * Diagnostic images - default is null, enable diagnostics=true to populate this parameter with one image per field
   * @member {Array.<String>} Diagnostics
   */
  exports.prototype['Diagnostics'] = undefined;
  /**
   * Optional; populated when using photo/recognize/form/advanced with the Setting Name of the best-matching highest-relevance form
   * @member {String} BestMatchFormSettingName
   */
  exports.prototype['BestMatchFormSettingName'] = undefined;



  return exports;
}));


