/**
 * ocrapi
 * The powerful Optical Character Recognition (OCR) APIs let you convert scanned images of pages into recognized text.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CloudmersiveOcrApiClientAsync) {
      root.CloudmersiveOcrApiClientAsync = {};
    }
    root.CloudmersiveOcrApiClientAsync.GetPageAngleResult = factory(root.CloudmersiveOcrApiClientAsync.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The GetPageAngleResult model module.
   * @module model/GetPageAngleResult
   * @version 1.3.3
   */

  /**
   * Constructs a new <code>GetPageAngleResult</code>.
   * Result of performing a get-page-angle operation
   * @alias module:model/GetPageAngleResult
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>GetPageAngleResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetPageAngleResult} obj Optional instance to populate.
   * @return {module:model/GetPageAngleResult} The populated <code>GetPageAngleResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Successful')) {
        obj['Successful'] = ApiClient.convertToType(data['Successful'], 'Boolean');
      }
      if (data.hasOwnProperty('Angle')) {
        obj['Angle'] = ApiClient.convertToType(data['Angle'], 'Number');
      }
    }
    return obj;
  }

  /**
   * True if the operation was successful, false otherwise
   * @member {Boolean} Successful
   */
  exports.prototype['Successful'] = undefined;
  /**
   * Angle of the page in radians; 0 represents perfectly horizontal
   * @member {Number} Angle
   */
  exports.prototype['Angle'] = undefined;



  return exports;
}));


